/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  moduleNameMapper: {
    '^@controllers/(.*)$': '<rootDir>/src/controllers/$1',
    '^@controllers$': '<rootDir>/src/controllers',
    '^@config/(.*)$': '<rootDir>/src/config/$1',
    '^@config$': '<rootDir>/src/config',
    '^@middlewares/(.*)$': '<rootDir>/src/middlewares/$1',
    '^@middlewares$': '<rootDir>/src/middlewares',
    '^@models/(.*)$': '<rootDir>/src/models/$1',
    '^@models$': '<rootDir>/src/models',
    '^@repositories/(.*)$': '<rootDir>/src/repositories/$1',
    '^@repositories$': '<rootDir>/src/repositories',
    '^@routes/(.*)$': '<rootDir>/src/routes/$1',
    '^@routes$': '<rootDir>/src/routes',
    '^@v1routes/(.*)$': '<rootDir>/src/routes/v1/$1',
    '^@v1routes$': '<rootDir>/src/routes/v1',
    '^@services/(.*)$': '<rootDir>/src/services/$1',
    '^@services$': '<rootDir>/src/services',
    '^@types/(.*)$': '<rootDir>/src/types/$1',
    '^@types$': '<rootDir>/src/types',
    '^@helpers/(.*)$': '<rootDir>/src/utils/helpers/$1',
    '^@helpers$': '<rootDir>/src/utils/helpers',
    '^@errors/(.*)$': '<rootDir>/src/utils/errors/$1',
    '^@errors$': '<rootDir>/src/utils/errors',
    '^@common/(.*)$': '<rootDir>/src/utils/common/$1',
    '^@common$': '<rootDir>/src/utils/common',
    '^@validators/(.*)$': '<rootDir>/src/validators/$1',
    '^@validators$': '<rootDir>/src/validators',
    '^uuid$': '<rootDir>/src/__tests__/__mocks__/uuid.js',
  },
  testMatch: ['**/__tests__/**/*.test.ts'],
};
